{% set name = "suitcase-tiff" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c4083f38e7a17c95f208637be151af69deff8ed8097409f89933288e0c2743f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - event-model >=1.8.0
    - setuptools
    - suitcase-utils
    - tifffile

test:
  requires:
    - python {{ python_min }}
  imports:
    - suitcase.tiff_series
    - suitcase.tiff_series.tests
    - suitcase.tiff_stack
    - suitcase.tiff_stack.tests

about:
  home: https://blueskyproject.io/suitcase
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents to TIFF
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-tiff

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
